
services:
  api:
    container_name: testrestapi
    build:
      context: .
      dockerfile: dockerfile

    env_file:
      - .env
    ports:
      - 8080:8080

    # This command replicates the mapping of volumes in the command
    # >> docker run -p 8080:8080 --rm -v $(pwd):/app -v /app/tmp --name testrestapi_container testrestapi
    volumes:
      - .:/app
      - tmp:/app/tmp
  db:
    container_name: testrestdb
    image: postgres:17.4-alpine3.21
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_NAME}
    ports:
      - 5432:5432
    volumes:
      - postgres-db:/var/lib/postgresql/data

volumes:
  postgres-db:
  tmp: